# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sefer Similarity Map
tagline:          'Visualizing the landscape of Jewish texts.'
description:      'Sefer Similarity Map'
url:              https://jhostyk.github.io/
baseurl:          /

author:
  name:           'Joseph HOstyk'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jhostyk/jhostyk.github.io
