# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sefer Similarity Map
tagline:          'Visualizing the landscape of Jewish texts.'
description:      'Visualizing the landscape of Jewish texts.'
url:              https://jhostyk.github.io/
baseurl:          /

author:
  name:           'Joseph Hostyk'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jhostyk/jhostyk.github.io
